name: taskly
description: "A simple and intuitive task manager built with Flutter."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.4
  intl: ^0.20.2
  provider: ^6.1.2
  flutter_slidable: ^3.1.1
  file_picker: ^8.1.2
  shared_preferences: ^2.3.2
  desktop_window: ^0.4.2
  get_it: ^7.7.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  generate: true
